Repository Linuxbrew/homebrew-test-bot, pull requests merged in 2018-08, with the labels that each got.

#100 Merge https://github.com/Homebrew/homebrew-test-bot/pull/170
  cmd/brew-test-bot.rb
Labels: merge

#102 Add option --skip-dependents
  cmd/brew-test-bot.rb
Labels: enhancement

#103 Print start_commit and end_commit
  cmd/brew-test-bot.rb
Labels: enhancement

#104 Deduplicate the list of updated bottles [Linux]
  cmd/brew-test-bot.rb
Labels: bug
